// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: pubmsg.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PubMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientID string `protobuf:"bytes,1,opt,name=clientID,proto3" json:"clientID,omitempty"` // ClientID
	Guid     string `protobuf:"bytes,2,opt,name=guid,proto3" json:"guid,omitempty"`         // guid
	Subject  string `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`   // subject
	Reply    string `protobuf:"bytes,4,opt,name=reply,proto3" json:"reply,omitempty"`       // optional reply
	Data     []byte `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`         // payload
	Sha256   []byte `protobuf:"bytes,10,opt,name=sha256,proto3" json:"sha256,omitempty"`    // optional sha256 of data
}

func (x *PubMsg) Reset() {
	*x = PubMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pubmsg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PubMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PubMsg) ProtoMessage() {}

func (x *PubMsg) ProtoReflect() protoreflect.Message {
	mi := &file_pubmsg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PubMsg.ProtoReflect.Descriptor instead.
func (*PubMsg) Descriptor() ([]byte, []int) {
	return file_pubmsg_proto_rawDescGZIP(), []int{0}
}

func (x *PubMsg) GetClientID() string {
	if x != nil {
		return x.ClientID
	}
	return ""
}

func (x *PubMsg) GetGuid() string {
	if x != nil {
		return x.Guid
	}
	return ""
}

func (x *PubMsg) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *PubMsg) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

func (x *PubMsg) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *PubMsg) GetSha256() []byte {
	if x != nil {
		return x.Sha256
	}
	return nil
}

var File_pubmsg_proto protoreflect.FileDescriptor

var file_pubmsg_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x70, 0x75, 0x62, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04,
	0x6d, 0x61, 0x69, 0x6e, 0x22, 0x94, 0x01, 0x0a, 0x06, 0x50, 0x75, 0x62, 0x4d, 0x73, 0x67, 0x12,
	0x1a, 0x0a, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x67,
	0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x67, 0x75, 0x69, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x65, 0x70,
	0x6c, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x68, 0x61, 0x32, 0x35, 0x36, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x06, 0x73, 0x68, 0x61, 0x32, 0x35, 0x36, 0x42, 0x0a, 0x5a, 0x08, 0x2e,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pubmsg_proto_rawDescOnce sync.Once
	file_pubmsg_proto_rawDescData = file_pubmsg_proto_rawDesc
)

func file_pubmsg_proto_rawDescGZIP() []byte {
	file_pubmsg_proto_rawDescOnce.Do(func() {
		file_pubmsg_proto_rawDescData = protoimpl.X.CompressGZIP(file_pubmsg_proto_rawDescData)
	})
	return file_pubmsg_proto_rawDescData
}

var file_pubmsg_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pubmsg_proto_goTypes = []interface{}{
	(*PubMsg)(nil), // 0: main.PubMsg
}
var file_pubmsg_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pubmsg_proto_init() }
func file_pubmsg_proto_init() {
	if File_pubmsg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pubmsg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PubMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pubmsg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pubmsg_proto_goTypes,
		DependencyIndexes: file_pubmsg_proto_depIdxs,
		MessageInfos:      file_pubmsg_proto_msgTypes,
	}.Build()
	File_pubmsg_proto = out.File
	file_pubmsg_proto_rawDesc = nil
	file_pubmsg_proto_goTypes = nil
	file_pubmsg_proto_depIdxs = nil
}
